version: '2'

services:
  gt-keycloak:
    image: quay.io/keycloak/keycloak:10.0.2
    container_name: baseFePrimeFlex3-projeto-keycloak
    volumes: 
        - ./keycloak/realm-export.json:/keycloak/realm-export.json
    ports:
      - 8084:8080
    environment:
      KEYCLOAK_IMPORT: /keycloak/realm-export.json
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2

